#+TITLE: Emacs Configuration
This file contains every thing from [[https://github.com/neppramod/java_emacs/blob/master/emacs-configuration.org][Java Programming in Emacs]] and more

* Setup
  Since this is an org file, I am using ~org-babel-load-file~ command to load this file from [[init.el]] file. Emacs loads [[init.el]] when it starts. I have setup a variable called ~EMACS_DIR~ to point to *.emacs.d* as the setup directory. Adjust it to match your system. To speed up loading time of emacs, I have ~used gc-cons-threshold~ and ~gc-cons-percentage~ variables, before and after loading this configuration file. I have set ~gc-cons-threshold~ value to 300 mb after startup. Adjust it to comfortable value according to memory in your system. ~lsp-java~ package however has ~1GB~ setup as default.


** Setup repository in org file
In the following code block, we will initialize package repositories and after that install ~use-package~. This package is used to install other packages.

 #+BEGIN_SRC emacs-lisp
 (require 'package)

 (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                          ("elpa" . "https://elpa.gnu.org/packages/")
			  ("org" . "https://orgmode.org/elpa/")
 ))


 (package-initialize)

 ; Fetch the list of packages available 
 (unless package-archive-contents (package-refresh-contents))

 ; Install use-package
 (setq package-list '(use-package))
 (dolist (package package-list)
 (unless (package-installed-p package) (package-install package)))
 #+END_SRC

 
** Looks
#+BEGIN_SRC emacs-lisp

  ;; Theme
  (load-theme 'tsdh-dark)

  ;; Font
  (add-to-list 'default-frame-alist '(font . "DejaVu Sans Mono-14"))

  ;; Hide Menubar, toolbar and scrollbar
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  ;; Inhibit startup screen and make scratch buffer clean
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message "")

  ;; Enable soft-wrap. Also set syntax highlighting for longer lines
  (global-visual-line-mode 1)
  (setq whitespace-line-column 1000) 

  ;; Set language and coding system to UTF-8
  (set-language-environment "UTF-8")

  ;; Disable annoying ring-bell when backspace key is pressed
  (setq ring-bell-function 'ignore)

  ;; Maintain a list of recent files opened
  (recentf-mode 1)
  (setq recentf-max-saved-items 50)

  ;; Coding (Enable ending brackets)
  (electric-pair-mode 1)

  ;; Set tab width for codign to 4
  (setq c-basic-offset 4)
#+END_SRC

