#+TITLE: Emacs Configuration
This file contains every thing from [[https://github.com/neppramod/java_emacs/blob/master/emacs-configuration.org][Java Programming in Emacs]] and more

* Setup
Since this is an org file, I am using ~org-babel-load-file~ command to load this file from [[init.el]] file. Emacs loads [[init.el]] when it starts. I have setup a variable called ~EMACS_DIR~ to point to *.emacs.d* as the setup directory. Adjust it to match your system. To speed up loading time of emacs, I have ~used gc-cons-threshold~ and ~gc-cons-percentage~ variables, before and after loading this configuration file. I have set ~gc-cons-threshold~ value to 300 mb after startup. Adjust it to comfortable value according to memory in your system. ~lsp-java~ package however has ~1GB~ setup as default.

** Setup repository in org file
In the following code block, we will initialize package repositories and after that install ~use-package~. This package is used to install other packages.

#+BEGIN_SRC emacs-lisp
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("elpa" . "https://elpa.gnu.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ))


  (package-initialize)

                                          ; Fetch the list of packages available 
  (unless package-archive-contents (package-refresh-contents))

                                          ; Install use-package
  (setq package-list '(use-package))
  (dolist (package package-list)
    (unless (package-installed-p package) (package-install package)))
#+END_SRC

** Looks
#+BEGIN_SRC emacs-lisp


  (use-package emacs
  :init
  ;; Add all your customizations prior to loading the themes
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs nil
        modus-themes-region '(bg-only no-extend))
  :config
  ;; Load the theme of your choice:
  (load-theme 'modus-operandi) ;; OR (load-theme 'modus-vivendi)
  :bind ("<f5>" . modus-themes-toggle))
  ;; Font
  (add-to-list 'default-frame-alist '(font . "Hack-15"))

  ;; Hide Menubar, toolbar and scrollbar
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (fringe-mode -1)

  ;; Inhibit startup screen and make scratch buffer clean
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message "")

  ;; Enable soft-wrap. Also set syntax highlighting for longer lines
  (global-visual-line-mode 1)
  (setq whitespace-line-column 1000) 

  ;; Set language and coding system to UTF-8
  (set-language-environment "UTF-8")

  ;; Disable annoying ring-bell when backspace key is pressed
  (setq ring-bell-function 'ignore)

  ;; Maintain a list of recent files opened
  (recentf-mode 1)
  (setq recentf-max-saved-items 50)

  ;; Coding (Enable ending brackets)
  (electric-pair-mode 1)

  ;; Change yes/no to y/n
  (fset 'yes-or-no-p 'y-or-n-p)

  ;; Tab space
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4)
  (setq indent-line-function 'insert-tab)
#+END_SRC


** Environment Setup
In some operating systems Emacs does not load environment variables properly. Therefore, below we install a package called ~exec-path-from-shell~ and initialize it.
#+begin_src emacs-lisp
  (use-package exec-path-from-shell :ensure t)
  (exec-path-from-shell-initialize)
#+end_src

** Operating System specific variable setup
Since we want to use same emacs configuration for each of our operating systems, we want to separate values that are different between different operating systems. In my setup, I have different values for ~JAVA_HOME~ in my linux.el and mac.el. Adjust these values accordingly for your setup if you are using different versions of Java. Following code loads mac.el, linux.el or windows.el based on where you run this configuration.

#+BEGIN_SRC emacs-lisp
  ;; Load platform specific variables using specific files. E.g linux.el. 
  ;; Make necessary changes as needed
  (cond ((eq system-type 'windows-nt) (load (concat EMACS_DIR "windows")))
        ((eq system-type 'gnu/linux) (load (concat EMACS_DIR "linux")))
        ((eq system-type 'darwin) (load (concat EMACS_DIR "mac")))
        (t (load-library "default")))
#+END_SRC

** Disable ansi color in compilation mode
#+begin_src emacs-lisp
  (defun my/ansi-colorize-buffer ()
    (let ((buffer-read-only nil))
      (ansi-color-apply-on-region (point-min) (point-max))))

  (use-package ansi-color
    :ensure t
    :config
    (add-hook 'compilation-filter-hook 'my/ansi-colorize-buffer)
    )
#+end_src

* Project Management and Coding
** Helm
Helm allows for easy completion of commands.
#+begin_src emacs-lisp
  (use-package helm
    :ensure t
    :init
    (helm-mode 1)
    (progn (setq helm-buffers-fuzzy-matching t)))


#+end_src

** Projectile
Use various utilities for managing project.
#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :custom
    ((projectile-completion-system 'helm))
    :ensure t
    :init
    (projectile-mode +1)
    :config
    (define-key projectile-mode-map (kbd "C-'") 'projectile-command-map)
    )
#+end_src

** Magit 
Magit works with git projects
#+begin_src emacs-lisp
  (use-package magit :ensure t)
#+end_src

** Yasnippet
Yasnippet is a template system for Emacs.
#+begin_src emacs-lisp
  (use-package yasnippet :ensure t :config (yas-global-mode 1))
  (use-package yasnippet-snippets :ensure t)
#+end_src

** Quickrun
We can use quickrun package to execute code (if it has main).
#+begin_src emacs-lisp
  (use-package quickrun
    :ensure t
    :bind ("C-c r" . 'myquickrun))

  (defun myquickrun()
    (interactive)
    (save-buffer)
    (quickrun))

#+end_src
** Expand Region
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :bind ("C-=" . er/expand-region))
#+END_SRC

* Custom Commands
#+begin_src emacs-lisp
  ;; Helm replace popular commands
  (global-set-key (kbd "C-c f") 'helm-recentf)
  (global-set-key (kbd "M-x") 'helm-M-x)
  (global-set-key (kbd "C-x C-f") 'helm-find-files)
  (global-set-key (kbd "M-y") 'helm-show-kill-ring)
#+end_src

* Custom Script
My custom script
#+begin_src emacs-lisp
  (org-babel-load-file "~/.emacs.d/custom.org")
#+end_src
