
** Custom Packages
   Following packages require special setup and configuration. Install them
   by following following instructions.
   *Note*: If you don't want to enable any package either remove that section or for ~use-package~ change ~:ensure t~ to ~:disabled t~ 
  

*** Org2Blog
   
   Write blog posts to wordpress with below basic setup. Change ~disabled~ to ~ensure~
   #+BEGIN_SRC emacs-lisp
   (use-package org2blog :ensure t)
   (setq org2blog/wp-blog-alist
      '(("<a profile name for this blog>"
         :url "https://<prefix>.wordpress.com/xmlrpc.php"
         :username "<username>")))
   #+END_SRC

   - Assign a profile and replace <prefix> and <username> with your blog's appropriately
   - Login to your website using ~M-x org2blog-user-login~
   - Once logged in you can manage your blog using ~M-x org2blog-user-interface~
   - The user interface has shortcut keys for most of the options. E.g. You can press ~e~ to create a new blog, ~l~ to publish post, ~k~ to view post and ~;~ to delete post
   - Once you create a buffer save it as org file, and then you can keep on updating it and publish new contents.
   
   
